server:
  port: 8083

product:
  service:
    message: "Bienvenue dans ProductMS !"
    
management:
  endpoints:
    jmx:
      exposure:
        include: refresh

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
