spring:
  application:
    name: ProductMs

server:
  port: 8083

product:
  service:
    message: "Bienvenue dans ProductMS !"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka
